version: "3.9"
services:

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://[user]:[password]@alkemy-java2.tmcemit.mongodb.net/tp?retryWrites=true&w=majority&appName=Alkemy-Java2

  mongodb:
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=[user]
      - MONGODB_INITDB_ROOT_PASSWORD=[password]
      - MONGO_INITDB_DATABASE=tp
    ports:
      - 27019:27017
    networks:
      - spring-network
    volumes:
      - data:/data/db
      - config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "-u", "user", "-p", "pass", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 10
networks:
  spring-network:
    driver: bridge
volumes:
  data:
  config: