### Create a new user
POST http://localhost:8080/api/productos
Content-Type: application/json

{
  "nombre": "Lapicera",
  "descripcion": "Lapicera azul para escribir. No se borra.",
  "precio": 1500,
  "stock": 100
}

$ curl -X POST http://localhost:8080/api/productos   -H "Content-Type: application/json"   -d '{"nombre": "Patito","descripcion": "Amarillo. Ideal para la ducha.","precio": 1500,"stock": 80}'


curl -X DELETE http://localhost:8080/api/productos/683cc8c489e0ce6ecbae1607   -H "Content-Type: application/json"   -d '{"nombre": "Patito","descripcion": "Amarillo. Ideal para la ducha.","precio": 1500,"stock": 80}'
